# my-bill-tracker/docker-compose.yaml
version: '3.8'

services:
  db:
    build:
      context: ../backend/db
      dockerfile: Dockerfile
    image: mysql:8.0
    container_name: bill-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: bill_tracker_db
      MYSQL_USER: bill_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    volumes:
      - ../backend/db/db-init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  api-gateway:
    build:
      context: ../backend/api-gateway
      dockerfile: Dockerfile
    container_name: bill-tracker-api-gateway
    ports:
      - "8443:8443"
    environment:
      - CORS_ALLOWED_ORIGINS=https://192.168.1.100:8443
    volumes:
      - ../backend/api-gateway/certs:/usr/src/app/certs:z
    depends_on:
      - user-service
      - organization-service
      - bill-payment-service
      - notification-service
      - bill-tracker-frontend
    restart: always

  user-service:
    build:
      context: ../backend/user-service
      dockerfile: Dockerfile
    container_name: bill-tracker-user-service
    # ports: - "3000:3000" 
    environment:
      DB_HOST: db
      DB_USER: bill_user
      DB_PASSWORD: your_db_password
      DB_NAME: bill_tracker_db
      DB_PORT: 3306
      SERVICE_PORT: 3000
      JWT_SECRET: your_jwt_secret_key_very_long_and_random
    depends_on:
      db:
        condition: service_healthy
    restart: always

  organization-service:
    build:
      context: ../backend/organization-service
      dockerfile: Dockerfile
    container_name: bill-tracker-organization-service
    # ports: - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: bill_user
      DB_PASSWORD: your_db_password
      DB_NAME: bill_tracker_db
      DB_PORT: 3306
      SERVICE_PORT: 3001
      JWT_SECRET: your_jwt_secret_key_very_long_and_random
    depends_on:
      db:
        condition: service_healthy
    restart: always

  bill-payment-service:
    build:
      context: ../backend/bill-payment-service
      dockerfile: Dockerfile
    container_name: bill-tracker-bill-payment-service
    # ports: - "3002:3002" 
    environment:
      DB_HOST: db
      DB_USER: bill_user
      DB_PASSWORD: your_db_password
      DB_NAME: bill_tracker_db
      DB_PORT: 3306
      SERVICE_PORT: 3002
      JWT_SECRET: your_jwt_secret_key_very_long_and_random
    depends_on:
      db:
        condition: service_healthy
      organization-service:
        condition: service_started
    restart: always

  notification-service:
    build:
      context: ../backend/notification-service
      dockerfile: Dockerfile
    container_name: bill-tracker-notification-service
    # ports: - "3003:3003"
    environment:
      DB_HOST: db
      DB_USER: bill_user
      DB_PASSWORD: your_db_password
      DB_NAME: bill_tracker_db
      DB_PORT: 3306
      SERVICE_PORT: 3003
      JWT_SECRET: your_jwt_secret_key_very_long_and_random
      EMAIL_SERVICE_HOST: smtp.sendgrid.net
      EMAIL_SERVICE_PORT: 587
      EMAIL_SERVICE_SECURE: false
      EMAIL_SERVICE_USER: apikey
      EMAIL_SERVICE_PASS: YOUR_SENDGRID_API_KEY
      EMAIL_FROM_ADDRESS: no-reply@yourdomain.com
    depends_on:
      db:
        condition: service_healthy
    restart: always

  bill-tracker-frontend:
    build:
      context: ../my-bill-tracker-frontend
      dockerfile: Dockerfile
    container_name: bill-tracker-frontend
    environment:
      # This URL will be used by the frontend to call the gateway itself
      - API_GATEWAY_URL=https://192.168.1.100:8443 # Update with your API Gateway URL

volumes:
  db_data: