version: '3.8'

services:
  db:
    build:
      context: ../backend/db
      dockerfile: Dockerfile
    image: mysql:8.0
    container_name: bill-tracker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: your_strong_root_password
      MYSQL_DATABASE: bill_tracker_db
      MYSQL_USER: bill_user
      MYSQL_PASSWORD: your_db_password
    ports:
      - "3306:3306"
    volumes:
      #- ./backend/db/init_scripts:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always

  user-service:
    build:
      context: ../backend/user-service
      dockerfile: Dockerfile
    container_name: bill-tracker-user-service
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: bill_user
      DB_PASSWORD: your_db_password
      DB_NAME: bill_tracker_db
      DB_PORT: 3306
      SERVICE_PORT: 3000
      JWT_SECRET: your_jwt_secret_key_very_long_and_random # Match this!
    depends_on:
      db:
        condition: service_healthy
    restart: always

  organization-service:
    build:
      context: ../backend/organization-service
      dockerfile: Dockerfile
    container_name: bill-tracker-organization-service
    ports:
      - "3001:3001"
    environment:
      DB_HOST: db
      DB_USER: bill_user
      DB_PASSWORD: your_db_password
      DB_NAME: bill_tracker_db
      DB_PORT: 3306
      SERVICE_PORT: 3001
      JWT_SECRET: your_jwt_secret_key_very_long_and_random # Match this!
    depends_on:
      db:
        condition: service_healthy
    restart: always

  bill-payment-service:
    build:
      context: ../backend/bill-payment-service # Path to your Dockerfile for this service
      dockerfile: Dockerfile
    container_name: bill-tracker-bill-payment-service
    ports:
      - "3002:3002" # Map service port to host port
    environment:
      DB_HOST: db
      DB_USER: bill_user
      DB_PASSWORD: your_db_password
      DB_NAME: bill_tracker_db
      DB_PORT: 3306
      SERVICE_PORT: 3002
      JWT_SECRET: your_jwt_secret_key_very_long_and_random # ⚠️ Add this line, match User Service's secret!
    depends_on:
      db:
        condition: service_healthy
      organization-service: # Also depends on organization service for linking bills to orgs
        condition: service_started
    restart: always

  bill-tracker-frontend:
    build:
      context: ../my-bill-tracker-frontend
      dockerfile: Dockerfile
    container_name: bill-tracker-frontend
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
      organization-service:
        condition: service_started

volumes:
  db_data: